"""Update Contrato and add Altura model

Revision ID: 9dea87e14666
Revises: c2f750849467
Create Date: 2026-02-25 23:16:19.628068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_postgresql_enum import TableReference
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9dea87e14666'
down_revision: Union[str, Sequence[str], None] = 'c2f750849467'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tipo', postgresql.ENUM('PF', 'PJ', name='tipocliente', create_type=False), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', postgresql.ENUM('ENABLE', 'DISABLE', 'DELETED', name='objectstatus', create_type=False), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('terreno',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('status', postgresql.ENUM('ENABLE', 'DISABLE', 'DELETED', name='objectstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('lat BETWEEN -90 AND 90', name='ck_terreno_lat_range'),
    sa.CheckConstraint('lng BETWEEN -180 AND 180', name='ck_terreno_lng_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('status', postgresql.ENUM('ENABLE', 'DISABLE', 'DELETED', name='objectstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('cliente_pf',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_table('cliente_pj',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cnpj', sa.String(length=18), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['cliente.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj')
    )
    op.create_table('torre',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('terreno_id', sa.Integer(), nullable=False),
    sa.Column('altura', sa.Integer(), nullable=False, comment='Altura em metros'),
    sa.Column('tipo', postgresql.ENUM('ESTAIADA', 'AUTO_LINEAR', 'AUTO_MISTA', 'AUTO_TRIAN', 'OUTRO', name='tipotorre', create_type=False), nullable=False),
    sa.Column('status', postgresql.ENUM('ENABLE', 'DISABLE', 'DELETED', name='objectstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['terreno_id'], ['terreno.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('contrato',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_inicial', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_final', sa.DateTime(timezone=True), nullable=False),
    sa.Column('recorrencia', postgresql.ENUM('MENSAL', 'ANUAL', 'UNICA', name='recorrenciacontrato', create_type=False), nullable=False),
    sa.Column('torre_id', sa.Uuid(), nullable=False),
    sa.Column('cliente_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['torre_id'], ['torre.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('despesa_torre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('torre_id', sa.Uuid(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(), nullable=True),
    sa.Column('recorrencia', postgresql.ENUM('UNICA', 'DIARIA', 'MENSAL', 'ANUAL', name='recorrenciadespesa', create_type=False), nullable=False),
    sa.Column('perpetua', sa.Boolean(), nullable=False),
    sa.Column('data_inicio', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_final', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['torre_id'], ['torre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documento_torre',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=100), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('torre_id', sa.Uuid(), nullable=False),
    sa.Column('status', postgresql.ENUM('ENABLE', 'DISABLE', 'DELETED', name='objectstatus', create_type=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['torre_id'], ['torre.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('altura',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('metro_inicial', sa.Integer(), nullable=False),
    sa.Column('metro_final', sa.Integer(), nullable=False),
    sa.Column('face', postgresql.ENUM('NORTE', 'SUL', 'LESTE', 'OESTE', name='facedirecao', create_type=False), nullable=False),
    sa.Column('contrato_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['contrato_id'], ['contrato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.sync_enum_values(
        enum_schema='public',
        enum_name='recorrenciacontrato',
        new_values=['MENSAL', 'ANUAL', 'UNICA'],
        affected_columns=[TableReference(table_schema='public', table_name='contrato', column_name='recorrencia')],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema='public',
        enum_name='recorrenciacontrato',
        new_values=['MENSAL', 'ANUAL'],
        affected_columns=[TableReference(table_schema='public', table_name='contrato', column_name='recorrencia')],
        enum_values_to_rename=[],
    )
    op.drop_table('altura')
    op.drop_table('documento_torre')
    op.drop_table('despesa_torre')
    op.drop_table('contrato')
    op.drop_table('torre')
    op.drop_table('cliente_pj')
    op.drop_table('cliente_pf')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('terreno')
    op.drop_table('cliente')
    # ### end Alembic commands ###
